webtalk_init -webtalk_dir C:/Users/erich/Documents/Digital_Designs/Xilinx/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/LoadTest_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 18 16:23:37 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b833b8cd58d05aa1b142d577fb5807bf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3c9dfcee4c12443abdf3a285ac8263a7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "201 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "12" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.62_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7100_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2749670656 -regid "" -xml C:/Users/erich/Documents/Digital_Designs/Xilinx/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/LoadTest_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/erich/Documents/Digital_Designs/Xilinx/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/LoadTest_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/erich/Documents/Digital_Designs/Xilinx/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/LoadTest_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
