# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/restricciones.xdc

# Block Designs: bd/DAC_test/DAC_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_test || ORIG_REF_NAME==DAC_test} -quiet] -quiet

# IP: bd/DAC_test/ip/DAC_test_clk_wiz_0_0/DAC_test_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_test_clk_wiz_0_0 || ORIG_REF_NAME==DAC_test_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DAC_test/ip/DAC_test_PWM_12b_0_0/DAC_test_PWM_12b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_test_PWM_12b_0_0 || ORIG_REF_NAME==DAC_test_PWM_12b_0_0} -quiet] -quiet

# IP: bd/DAC_test/ip/DAC_test_c_counter_binary_0_0/DAC_test_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_test_c_counter_binary_0_0 || ORIG_REF_NAME==DAC_test_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/DAC_test/ip/DAC_test_SineWave100s_0_0/DAC_test_SineWave100s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_test_SineWave100s_0_0 || ORIG_REF_NAME==DAC_test_SineWave100s_0_0} -quiet] -quiet

# IP: bd/DAC_test/ip/DAC_test_xlconstant_0_0/DAC_test_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_test_xlconstant_0_0 || ORIG_REF_NAME==DAC_test_xlconstant_0_0} -quiet] -quiet

# IP: bd/DAC_test/ip/DAC_test_comp2s12b_0_0/DAC_test_comp2s12b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_test_comp2s12b_0_0 || ORIG_REF_NAME==DAC_test_comp2s12b_0_0} -quiet] -quiet

# IP: bd/DAC_test/ip/DAC_test_PWM_12b_0_1/DAC_test_PWM_12b_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_test_PWM_12b_0_1 || ORIG_REF_NAME==DAC_test_PWM_12b_0_1} -quiet] -quiet

# IP: bd/DAC_test/ip/DAC_test_descomp2s12b_0_0/DAC_test_descomp2s12b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_test_descomp2s12b_0_0 || ORIG_REF_NAME==DAC_test_descomp2s12b_0_0} -quiet] -quiet

# IP: bd/DAC_test/ip/DAC_test_PWM_12b_1_0/DAC_test_PWM_12b_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_test_PWM_12b_1_0 || ORIG_REF_NAME==DAC_test_PWM_12b_1_0} -quiet] -quiet

# XDC: bd/DAC_test/DAC_test_ooc.xdc
