# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/erich/Documents/Digital_Designs/Xilinx/PruebaCargaRLC/PruebaCargaRLC.srcs/sources_1/bd/Full/ip/Full_c_counter_binary_1_0/Full_c_counter_binary_1_0.xci
# IP: The module: 'Full_c_counter_binary_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erich/Documents/Digital_Designs/Xilinx/PruebaCargaRLC/PruebaCargaRLC.srcs/sources_1/bd/Full/ip/Full_c_counter_binary_1_0/Full_c_counter_binary_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Full_c_counter_binary_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/erich/Documents/Digital_Designs/Xilinx/PruebaCargaRLC/PruebaCargaRLC.srcs/sources_1/bd/Full/ip/Full_c_counter_binary_1_0/Full_c_counter_binary_1_0.xci
# IP: The module: 'Full_c_counter_binary_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erich/Documents/Digital_Designs/Xilinx/PruebaCargaRLC/PruebaCargaRLC.srcs/sources_1/bd/Full/ip/Full_c_counter_binary_1_0/Full_c_counter_binary_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Full_c_counter_binary_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
