set_property SRC_FILE_INFO {cfile:C:/RaulEsteban/DIgitalDesigns/Xilinx/CA2Test/CA2Test.srcs/constrs_1/new/restricciones.xdc rfile:../../../CA2Test.srcs/constrs_1/new/restricciones.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports resetn_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports PWM_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports PWM_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports PWM_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 16 [get_ports PWM_0]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks VIRTUAL_clk_out2_DAC_test_clk_wiz_0_0] -min -add_delay 0.000 [get_ports PWM_0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks VIRTUAL_clk_out2_DAC_test_clk_wiz_0_0] -max -add_delay 2.000 [get_ports PWM_0]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports Sine_recomp]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports Sine]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports PWM_Ca2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name DAC_test_i/c_counter_binary_0/U0/i_synth/i_baseblox.i_baseblox_counter/THRESH0 -source [get_pins DAC_test_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT0] -divide_by 8 [get_pins DAC_test_i/c_counter_binary_0/U0/i_synth/i_baseblox.i_baseblox_counter/i_out_q_thresh0.q_thresh0_i_reg/Q]
