# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/restricciones.xdc

# Block Designs: bd/Load_Test/Load_Test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test || ORIG_REF_NAME==Load_Test} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_SineWave100s_0_0/Load_Test_SineWave100s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_SineWave100s_0_0 || ORIG_REF_NAME==Load_Test_SineWave100s_0_0} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_clk_wiz_0_0/Load_Test_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_clk_wiz_0_0 || ORIG_REF_NAME==Load_Test_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_c_counter_binary_0_0/Load_Test_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_c_counter_binary_0_0 || ORIG_REF_NAME==Load_Test_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_comp2s12b_0_1/Load_Test_comp2s12b_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_comp2s12b_0_1 || ORIG_REF_NAME==Load_Test_comp2s12b_0_1} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_xlconcat_0_0/Load_Test_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_xlconcat_0_0 || ORIG_REF_NAME==Load_Test_xlconcat_0_0} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_xlconstant_0_0/Load_Test_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_xlconstant_0_0 || ORIG_REF_NAME==Load_Test_xlconstant_0_0} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_PWM_12b_0_0/Load_Test_PWM_12b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_PWM_12b_0_0 || ORIG_REF_NAME==Load_Test_PWM_12b_0_0} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_descomp2s12b_0_0/Load_Test_descomp2s12b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_descomp2s12b_0_0 || ORIG_REF_NAME==Load_Test_descomp2s12b_0_0} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_PWM_12b_0_1/Load_Test_PWM_12b_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_PWM_12b_0_1 || ORIG_REF_NAME==Load_Test_PWM_12b_0_1} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_xlslice_0_0/Load_Test_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_xlslice_0_0 || ORIG_REF_NAME==Load_Test_xlslice_0_0} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_xlconstant_1_0/Load_Test_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_xlconstant_1_0 || ORIG_REF_NAME==Load_Test_xlconstant_1_0} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_c_counter_binary_0_1/Load_Test_c_counter_binary_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_c_counter_binary_0_1 || ORIG_REF_NAME==Load_Test_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_ModeloCarga_0_2/Load_Test_ModeloCarga_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_ModeloCarga_0_2 || ORIG_REF_NAME==Load_Test_ModeloCarga_0_2} -quiet] -quiet

# IP: bd/Load_Test/ip/Load_Test_util_vector_logic_0_0/Load_Test_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Load_Test_util_vector_logic_0_0 || ORIG_REF_NAME==Load_Test_util_vector_logic_0_0} -quiet] -quiet

# XDC: bd/Load_Test/Load_Test_ooc.xdc
