-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\matlabVHDL\Comparador.vhd
-- Created: 2017-05-30 14:00:36
-- 
-- Generated by MATLAB 8.6 and HDL Coder 3.7
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.5e-07
-- Target subsystem base rate: 1e-06
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Comparador
-- Source Path: matlabVHDL/Comparador
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Comparador IS
  PORT( count                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        PWM                               :   IN    real;  -- double
        y                                 :   OUT   real  -- double
        );
END Comparador;


ARCHITECTURE rtl OF Comparador IS

  -- Component Declarations
  COMPONENT MATLAB_Function
    PORT( count                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          PWM                             :   IN    real;  -- double
          y                               :   OUT   real  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MATLAB_Function
    USE ENTITY work.MATLAB_Function(rtl);

BEGIN
  u_MATLAB_Function : MATLAB_Function
    PORT MAP( count => count,  -- uint8
              PWM => PWM,  -- double
              y => y  -- double
              );

END rtl;

