-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\matlabVHDL\matlabVHDL.vhd
-- Created: 2017-05-30 13:33:20
-- 
-- Generated by MATLAB 8.6 and HDL Coder 3.7
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.5e-07
-- Target subsystem base rate: 1e-06
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- PWM                           ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: matlabVHDL
-- Source Path: matlabVHDL
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY matlabVHDL IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        PWM                               :   OUT   real  -- double
        );
END matlabVHDL;


ARCHITECTURE rtl OF matlabVHDL IS

  -- Component Declarations
  COMPONENT MATLAB_Function
    PORT( count                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          PWM                             :   IN    real;  -- double
          y                               :   OUT   real  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MATLAB_Function
    USE ENTITY work.MATLAB_Function(rtl);

  -- Signals
  SIGNAL enb_1_4_0                        : std_logic;
  SIGNAL Counter_Free_Running_out1        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant_out1                    : real := 0.0;  -- double
  SIGNAL y                                : real := 0.0;  -- double

BEGIN
  u_MATLAB_Function : MATLAB_Function
    PORT MAP( count => std_logic_vector(Counter_Free_Running_out1),  -- uint8
              PWM => Constant_out1,  -- double
              y => y  -- double
              );

  enb_1_4_0 <= clk_enable;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  Counter_Free_Running_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Counter_Free_Running_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_4_0 = '1' THEN
        Counter_Free_Running_out1 <= Counter_Free_Running_out1 + to_unsigned(16#01#, 8);
      END IF;
    END IF;
  END PROCESS Counter_Free_Running_process;


  Constant_out1 <= 200.0;

  ce_out <= clk_enable;

  PWM <= y;

END rtl;

