-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\carga_model\Subsystem.vhd
-- Created: 2018-11-10 17:36:47
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.0001
-- Target subsystem base rate: 0.0001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Hzout                         ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: carga_model/Subsystem
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ModeloCarga IS
  PORT( clk                               :   IN    std_logic;
        resetn                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Hzin                              :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        ce_out                            :   OUT   std_logic;
        Hzout                             :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END ModeloCarga;


ARCHITECTURE rtl OF ModeloCarga IS

  -- Signals
  SIGNAL enb_const_rate                   : std_logic;
  SIGNAL Hzin_signed                      : signed(15 DOWNTO 0);  -- int16
  SIGNAL s_input_acc_cast                 : signed(31 DOWNTO 0);  -- sfix32_En2
  SIGNAL s_state_out1                     : signed(31 DOWNTO 0);  -- int32
  SIGNAL s_state_out2_1                   : signed(31 DOWNTO 0);  -- int32
  SIGNAL denom_gain2_mul_temp             : signed(63 DOWNTO 0);  -- sfix64_En20
  SIGNAL s_denom_gain2                    : signed(31 DOWNTO 0);  -- sfix32_En2
  SIGNAL s_state_cast                     : signed(31 DOWNTO 0);  -- int32
  SIGNAL denom_gain1_mul_temp             : signed(63 DOWNTO 0);  -- sfix64_En20
  SIGNAL s_denom_gain1                    : signed(31 DOWNTO 0);  -- sfix32_En2
  SIGNAL s_denom_acc_out1                 : signed(31 DOWNTO 0);  -- sfix32_En2
  SIGNAL s_denom_acc_out2                 : signed(31 DOWNTO 0);  -- sfix32_En2
  SIGNAL nume_gain_b0_mul_temp            : signed(63 DOWNTO 0);  -- sfix64_En20
  SIGNAL s_nume_gain_b0                   : signed(31 DOWNTO 0);  -- sfix32_En2
  SIGNAL nume_gain1_mul_temp              : signed(63 DOWNTO 0);  -- sfix64_En20
  SIGNAL s_nume_gain1                     : signed(31 DOWNTO 0);  -- sfix32_En2
  SIGNAL s_nume_acc_out1                  : signed(31 DOWNTO 0);  -- sfix32_En2
  SIGNAL s_output_cast                    : signed(15 DOWNTO 0);  -- int16

BEGIN
  Hzin_signed <= signed(Hzin);

  s_input_acc_cast <= resize(Hzin_signed & '0' & '0', 32);

  enb_const_rate <= clk_enable;

  s_state_out2_process : PROCESS (clk, resetn)
  BEGIN
    IF resetn = '0' THEN
      s_state_out2_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_const_rate = '1' THEN
        s_state_out2_1 <= s_state_out1;
      END IF;
    END IF;
  END PROCESS s_state_out2_process;


  denom_gain2_mul_temp <= to_signed(1040712, 32) * s_state_out2_1;
  s_denom_gain2 <= denom_gain2_mul_temp(49 DOWNTO 18);

  s_state_out1_1_process : PROCESS (clk, resetn)
  BEGIN
    IF resetn = '0' THEN
      s_state_out1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_const_rate = '1' THEN
        s_state_out1 <= s_state_cast;
      END IF;
    END IF;
  END PROCESS s_state_out1_1_process;


  denom_gain1_mul_temp <= to_signed(-2089288, 32) * s_state_out1;
  s_denom_gain1 <= denom_gain1_mul_temp(49 DOWNTO 18);

  s_denom_acc_out1 <= s_input_acc_cast - s_denom_gain1;

  s_denom_acc_out2 <= s_denom_acc_out1 - s_denom_gain2;

  s_state_cast <= resize(s_denom_acc_out2(31 DOWNTO 2), 32);

  nume_gain_b0_mul_temp <= to_signed(39531, 32) * s_state_cast;
  s_nume_gain_b0 <= nume_gain_b0_mul_temp(49 DOWNTO 18);

  nume_gain1_mul_temp <= to_signed(-39531, 32) * s_state_out1;
  s_nume_gain1 <= nume_gain1_mul_temp(49 DOWNTO 18);

  s_nume_acc_out1 <= s_nume_gain_b0 + s_nume_gain1;

  s_output_cast <= s_nume_acc_out1(17 DOWNTO 2);

  Hzout <= std_logic_vector(s_output_cast);

  ce_out <= clk_enable;

END rtl;

