# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/erich/Documents/Digital_Designs/Xilinx/DAC_test/DAC_test.srcs/sources_1/bd/DAC_test/ip/DAC_test_c_counter_binary_0_0/DAC_test_c_counter_binary_0_0.xci
# IP: The module: 'DAC_test_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erich/Documents/Digital_Designs/Xilinx/DAC_test/DAC_test.srcs/sources_1/bd/DAC_test/ip/DAC_test_c_counter_binary_0_0/DAC_test_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_test_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/erich/Documents/Digital_Designs/Xilinx/DAC_test/DAC_test.srcs/sources_1/bd/DAC_test/ip/DAC_test_c_counter_binary_0_0/DAC_test_c_counter_binary_0_0.xci
# IP: The module: 'DAC_test_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erich/Documents/Digital_Designs/Xilinx/DAC_test/DAC_test.srcs/sources_1/bd/DAC_test/ip/DAC_test_c_counter_binary_0_0/DAC_test_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_test_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
