# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/erich/Documents/Digital_Designs/Xilinx/Load_Test/Load_Test.srcs/sources_1/bd/Load_Test/ip/Load_Test_c_counter_binary_0_0/Load_Test_c_counter_binary_0_0.xci
# IP: The module: 'Load_Test_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erich/Documents/Digital_Designs/Xilinx/Load_Test/Load_Test.srcs/sources_1/bd/Load_Test/ip/Load_Test_c_counter_binary_0_0/Load_Test_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Load_Test_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/erich/Documents/Digital_Designs/Xilinx/Load_Test/Load_Test.srcs/sources_1/bd/Load_Test/ip/Load_Test_c_counter_binary_0_0/Load_Test_c_counter_binary_0_0.xci
# IP: The module: 'Load_Test_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erich/Documents/Digital_Designs/Xilinx/Load_Test/Load_Test.srcs/sources_1/bd/Load_Test/ip/Load_Test_c_counter_binary_0_0/Load_Test_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Load_Test_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
