# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/restricciones.xdc

# Block Designs: bd/Full/Full.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full || ORIG_REF_NAME==Full} -quiet] -quiet

# IP: bd/Full/ip/Full_VielEntity_0_0/Full_VielEntity_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_VielEntity_0_0 || ORIG_REF_NAME==Full_VielEntity_0_0} -quiet] -quiet

# IP: bd/Full/ip/Full_clk_wiz_0_0/Full_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_clk_wiz_0_0 || ORIG_REF_NAME==Full_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Full/ip/Full_c_counter_binary_0_1/Full_c_counter_binary_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_c_counter_binary_0_1 || ORIG_REF_NAME==Full_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/Full/ip/Full_c_counter_binary_1_0/Full_c_counter_binary_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_c_counter_binary_1_0 || ORIG_REF_NAME==Full_c_counter_binary_1_0} -quiet] -quiet

# XDC: bd/Full/Full_ooc.xdc
