set_property SRC_FILE_INFO {cfile:C:/RaulEsteban/DIgitalDesigns/Xilinx/FastPinPmodTest/FastPinPmodTest.srcs/constrs_1/new/Restricciones.xdc rfile:../../../FastPinPmodTest.srcs/constrs_1/new/Restricciones.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports PWM_0]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports PWM_1]
